### ISSUE TITLE
Issue with socket.to(roomId).emit

### ISSUE THREAD

**Issue by hamidabdulmalik** [socketio/socket.io-deno#3]
There seems to be an issue with socket.to function. below is an image. Good job by the way
<img width="1440" alt="Screenshot 2022-09-24 at 11 08 59" src="https://user-images.githubusercontent.com/340532/192090118-3206ebbc-6b3d-4705-910b-4c84303f8133.png">

**Comment by darrachequesne** [comment]
Good catch! This should be fixed by https://github.com/socketio/socket.io-deno/commit/4ce5f646a95d9dd522fdf3c86951f82d641e3418.

**Comment by darrachequesne** [comment]
Released in [0.2.0](https://github.com/socketio/socket.io-deno/releases/tag/0.2.0).

Please reopen if needed!
